### ISSUE TITLE
Recursive calls don't get memoized with memoizeFix, when the recursive call uses higher numbers than the input.

### ISSUE THREAD

**Issue by Fybe** [Bodigrim/chimera#18]
The following script calculates the 50th fibonacci number by recursing upwards instead of downwards, with the base-cases being 49 and 50. I have added `traceShow`s to see, when recursive calls are not memoized.
```haskell
fib50F :: (Word -> Word) -> Word -> Word
fib50F _ 50 = traceShow 50 0
fib50F _ 49 = traceShow 49 1
fib50F f n  = traceShow n $ f (n+1) + f (n+2)

fib50 :: Word -> Word
fib50 = memoizeFix fib50F

main :: IO ()
main = do
  print $ fib50 0
```
Ideally, each number between 0 and 50 would only be printed once, but they are printed many times. In fact, the above code never finishes on my machine, whereas the usual memoized implementation finishes immediately.

**Comment by Fybe** [comment]
During yesterdays Advent of Code, you basically had to to calculate the number of possible paths from node 0 to node n in a graph, with edges such that the nodes on any path are increasing strictly monotone (i.e. 0 -> 3 -> 4 -> 7). I agree the above code is a pretty contrived example, but seemed simpler to explain than the code, where I discovered it.

**Comment by Bodigrim** [comment]
`chimera` assumes that 0 is the base case and puts no effort to memoize recursive calls inside:
https://github.com/Bodigrim/chimera/blob/28e0bc979b341d8dd891e896271ed7f401b1db95/Data/Chimera.hs#L231
This is fixable, but I need to assess consequences for other applications.

**Comment by Fybe** [comment]
Would you be open to a pull request?

**Comment by Bodigrim** [comment]
Of course. But I'll be a bit busy next days, I hope it's fine. 
Take care about the program quoted at https://github.com/Bodigrim/chimera#benchmarks - it should continue to work under your PR.

**Comment by Fybe** [comment]
I played with the code a bit, and figured after way too much time out, that it is not possible to memoize every recursive function call, while keeping the program you mentioned perfomant. The reason is, that the collatz sequence reaches very high numbers, for example `collatzF f 77671` will eventually try to call `f 1570824736` allocating at least 1570824736 Word * 8 Byte / Word = 12.5 GB when using boxed vectors. The memoize  package avoids this, by only partially allocating the search tree.

So I would suggest adding functions `tabulateFix'` and `memoizeFix'` for when full memoization is needed.
