### ISSUE TITLE
`fromListWithDef` diverges

### ISSUE THREAD

**Issue by pgujjula** [Bodigrim/chimera#39]
The following example diverges, with ghc-9.8.2 and ghc-9.6.4

```haskell
naturals :: UChimera Int
naturals = fromListWithDef 0 [0..]

main :: IO ()
main = print (index naturals 0)
```

If you can reproduce @Bodigrim, I can investigate and prepare a PR.

**Comment by Bodigrim** [comment]
Thanks, I can reproduce indeed.

**Comment by pgujjula** [comment]
Opened PR https://github.com/Bodigrim/chimera/pull/42 with a fix
