### ISSUE TITLE
iterate function

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/chimera#8]
Implement `iterate` function with semantics similar to `Data.List.iterate` and its monadic analogue `iterateM` both for `Data.Chimera` and `Data.Chimera.Unboxed`.

```haskell
iterate :: U.Unbox a => (a -> a) -> a -> Data.Chimera.Unboxed.Chimera a
iterate f = runIdentity . iterateM (return . f)

iterateM :: (Monad m, U.Unbox a) => (a -> m a) -> a -> m (Data.Chimera.Unboxed.Chimera a)
iterateM = undefined
```

**Comment by rockbmb** [comment]
Is this PR accepting public contributions? If so, can you add some more information to its issues?

**Comment by Bodigrim** [comment]
I'd definitely appreciate contributions! I've added more info, feel free to ask for details.
