### ISSUE TITLE
Rename with no information?

### ISSUE THREAD

**Issue by qrilka** [Bodigrim/chimera#9]
It looks like bit-stream was renamed to chimera without any signs about that and e.g. link from http://hackage.haskell.org/package/bit-stream leads to this repo which has a different name. It would be better if some information will be present both on Hackage for bit-stream and in this repo readme.

**Comment by Bodigrim** [comment]
Thanks, I've added a deprecation label to http://hackage.haskell.org/package/bit-stream. Sorry for inconvenience.

**Comment by qrilka** [comment]
It makes sense to replace it with chimera on Stackage too
